// Code generated by MockGen. DO NOT EDIT.
// Source: ./rbt/publisher.go

// Package mktools is a generated GoMock package.
package mktools

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRabbitPublisher is a mock of RabbitPublisher interface.
type MockRabbitPublisher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitPublisherMockRecorder[T]
}

// MockRabbitPublisherMockRecorder is the mock recorder for MockRabbitPublisher.
type MockRabbitPublisherMockRecorder[T any] struct {
	mock *MockRabbitPublisher[T]
}

// NewMockRabbitPublisher creates a new mock instance.
func NewMockRabbitPublisher[T any](ctrl *gomock.Controller) *MockRabbitPublisher[T] {
	mock := &MockRabbitPublisher[T]{ctrl: ctrl}
	mock.recorder = &MockRabbitPublisherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitPublisher[T]) EXPECT() *MockRabbitPublisherMockRecorder[T] {
	return m.recorder
}

// Publish mocks base method.
func (m *MockRabbitPublisher[T]) Publish(correlationId string, data T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", correlationId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRabbitPublisherMockRecorder[T]) Publish(correlationId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRabbitPublisher[T])(nil).Publish), correlationId, data)
}

// PublishForResult mocks base method.
func (m *MockRabbitPublisher[T]) PublishForResult(correlationId string, data T, exchange, routingKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishForResult", correlationId, data, exchange, routingKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishForResult indicates an expected call of PublishForResult.
func (mr *MockRabbitPublisherMockRecorder[T]) PublishForResult(correlationId, data, exchange, routingKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishForResult", reflect.TypeOf((*MockRabbitPublisher[T])(nil).PublishForResult), correlationId, data, exchange, routingKey)
}

// PublishTo mocks base method.
func (m *MockRabbitPublisher[T]) PublishTo(correlationId, exchange, routingKey string, data T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTo", correlationId, exchange, routingKey, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTo indicates an expected call of PublishTo.
func (mr *MockRabbitPublisherMockRecorder[T]) PublishTo(correlationId, exchange, routingKey, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTo", reflect.TypeOf((*MockRabbitPublisher[T])(nil).PublishTo), correlationId, exchange, routingKey, data)
}
